// <auto-generated />
using CasaApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CasaApp.Api.Migrations
{
    [DbContext(typeof(CasaDbContext))]
    partial class CasaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CasaApp.Api.Models.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("CasaApp.Api.Models.Plato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Platos");
                });

            modelBuilder.Entity("CasaApp.Api.Models.PlatoIngrediente", b =>
                {
                    b.Property<int>("PlatoId")
                        .HasColumnType("int");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PlatoId", "IngredienteId");

                    b.HasIndex("IngredienteId");

                    b.ToTable("PlatoIngredientes");
                });

            modelBuilder.Entity("CasaApp.Api.Models.PlatoIngrediente", b =>
                {
                    b.HasOne("CasaApp.Api.Models.Ingrediente", "Ingrediente")
                        .WithMany("Platos")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CasaApp.Api.Models.Plato", "Plato")
                        .WithMany("Ingredientes")
                        .HasForeignKey("PlatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Plato");
                });

            modelBuilder.Entity("CasaApp.Api.Models.Ingrediente", b =>
                {
                    b.Navigation("Platos");
                });

            modelBuilder.Entity("CasaApp.Api.Models.Plato", b =>
                {
                    b.Navigation("Ingredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
